.\" Original file was take from gzip, thus this man page is under GNU GPLv2+.
.TH XZDIFF 1 "2009-04-13" "XZ Utils"
.SH NAME
xzcmp, xzdiff, lzcmp, lzdiff \- compare .xz and .lzma compressed files
.SH SYNOPSIS
.B xzcmp
.RI [ cmp_options "] " file1 " [" file2 ]
.br
.B xzdiff
.RI [ diff_options "] " file1 " [" file2 ]
.br
.B lzcmp
.RI [ cmp_options "] " file1 " [" file2 ]
.br
.B lzdiff
.RI [ diff_options "] " file1 " [" file2 ]
.SH DESCRIPTION
.B  xzcmp
and
.B xdiff
are used to invoke the
.BR cmp (1)
or the
.BR diff (1)
program on compressed files.  All options specified are passed directly to
.B cmp
or
.BR diff "."
If only 1 file is specified, then the files compared are
.I file1
(which must have .xz or .lzma suffix) and
.I file1
from which the .xz or .lzma suffix has been stripped.
If two files are specified, then they are uncompressed if necessary and fed to
.B cmp
or
.BR diff "."
The exit status from
.B cmp
or
.B diff
is preserved.
.SH AUTHORS
This manual page was ripped from
.BR zdiff (1)
shipped in gzip package.
.SH "SEE ALSO"
.BR cmp (1),
.BR diff (1),
.BR xzmore(1),
.BR xzgrep(1),
.BR xz (1)
.SH BUGS
Messages from the
.B cmp
or
.B diff
programs refer to temporary filenames instead of those specified.
