.\" Original file was take from gzip, thus this man page is under GNU GPLv2+.
.TH XZGREP 1 "2009-04-13" "XZ Utils"
.SH NAME
xzgrep \- search .xz and .lzma compressed files for a regular expression
.SH SYNOPSIS
.B xzgrep
.RI [ grep_options ]
.RB  [ \-e ]
.I pattern
.IR filename ".\|.\|."
.br
.B xzegrep
.RB ...
.br
.B xzfgrep
.RB ...
.br
.B lzgrep
.RB ...
.br
.B lzegrep
.RB ...
.br
.B lzfgrep
.RB ...
.SH DESCRIPTION
.B  xzgrep
is used to invoke the
.BR grep (1)
on .xz or .lzma compressed files. All options specified are passed directly to
.BR grep .
If no file is specified, then the standard input is decompressed
if necessary and fed to grep.
Otherwise the given files are uncompressed if necessary and fed to
.BR grep .
.PP
If
.B xzgrep
is invoked as
.B xzegrep
or
.B xzfgrep
then
.B egrep
or
.B fgrep
is used instead of
.B grep.
The same applies to names
.BR lzgrep ,
.BR lzegrep ,
and
.BR lzfgrep ,
which are provided for backward compatibility with LZMA Utils.

If the GREP environment variable is set,
.B xzgrep
uses it as the
.B grep
program to be invoked. For example:

    for sh:  GREP=fgrep  xzgrep string files
    for csh: (setenv GREP fgrep; xzgrep string files)
.SH AUTHORS
Original
.BR zgrep (1)
manual page by Charles Levert <charles@comm.polymtl.ca>.
.PP
Minor modifications for XZ Utils by Lasse Collin
<lasse.collin@tukaani.org>.
.SH "SEE ALSO"
.BR grep (1),
.BR egrep (1),
.BR fgrep (1),
.BR xzdiff (1),
.BR xzmore (1),
.BR xz (1)
