.\" Original file was take from gzip, thus this man page is under GNU GPLv2+.
.TH XZMORE 1 "2009-04-13" "XZ Utils"
.SH NAME
xzmore, xzless, lzmore, lzless \- view .xz or .lzma compressed (text) files
.SH SYNOPSIS
.B xzmore
.RI [ "filename ..."  ]
.br
.B xzless
.RI [ "filename ..."  ]
.br
.B lzmore
.RI [ "filename ..."  ]
.br
.B lzless
.RI [ "filename ..."  ]
.SH DESCRIPTION
.B  xzmore
is a filter which allows examination of .xz or .lzma compressed text files
one screenful at a time on a soft-copy terminal.
.PP
To use a pager other than the default
.B more,
set environment variable
.B PAGER
to the name of the desired program, such as
.BR less .
If
.B xzmore
is called as
.B xzless
then
.B less
is used as the
.BR PAGER .
The names
.B lzmore
and
.B lzless
are provided for backward compatibility with LZMA Utils.
.TP
.BR e " or " q
When the prompt --More--(Next file:
.IR file )
is printed, this command causes xzmore to exit.
.TP
.B s
When the prompt --More--(Next file:
.IR file )
is printed, this command causes zmore to skip the next file and continue.
.PP
For list of keyboard commands supported while actually viewing the
content of a file, refer to manual of the pager you use, usually
.BR more (1)
or
.BR less (1).
.SH AUTHORS
This manual page was ripped from
.BR zmore (1)
shipped in gzip package.
.SH "SEE ALSO"
.BR more (1),
.BR zmore (1),
.BR xzdiff (1),
.BR xzgrep (1),
.BR xz (1)
