# SPDX-License-Identifier: 0BSD

name: FreeBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions: {}

jobs:
  FreeBSD:
    strategy:
      matrix:
        include:
          - version: 12.4
            arch: x86_64
          - version: 14.2
            arch: aarch64
          - version: 15.0
            arch: x86_64

    runs-on: ubuntu-latest

    name: FreeBSD

    steps:
      - uses: actions/checkout@v4

      - name: Test in FreeBSD
        uses: vmactions/FreeBSD-vm@c3ae29a132c8ef1924775414107a97cac042aad5 #v1.2.0
        with:
          release: ${{ matrix.release }}
          arch: ${{ matrix.arch }}
          usesh: true
          prepare: >
            pkg install -y
            autoconf
            automake
            gettext-tools
            libtool
            m4
            po4a
          run: |
            set -e
            export LC_ALL=C LANG=C
            uname -a
            ./autogen.sh
            ./configure --disable-static --enable-debug --enable-werror
            make -j4 check
