# SPDX-License-Identifier: 0BSD

name: OpenBSD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions: {}

jobs:
  OpenBSD:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: OpenBSD
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Test in OpenBSD
        uses: vmactions/openbsd-vm@3fafb45f2e2e696249c583835939323fe1c3448c #v1.3.7
        with:
          usesh: true
          prepare: >
            /usr/sbin/pkg_add -I -v
            autoconf-2.72p0
            automake-1.17
            gettext-tools
            libtool
            m4
          run: |
            set -e
            export AUTOCONF_VERSION=2.72
            export AUTOMAKE_VERSION=1.17
            uname -a
            ./autogen.sh --no-po4a
            ./configure --disable-static --enable-debug --enable-werror --disable-nls --enable-external-sha256
            make -j4 check
