# SPDX-License-Identifier: 0BSD

name: Solaris

on:
  push:
    branches: [ master, ci_run ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Solaris:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Solaris
    steps:
      - uses: actions/checkout@v7

      - name: Test in Solaris
        uses: vmactions/solaris-vm@v1
        with:
          release: 11.4-gcc
          usesh: true
          run: |
            set -e
            uname -a
            # /usr/xpg4/bin isn't in PATH by default.
            echo "Environment variable PATH: $PATH"
            ./autogen.sh --no-po4a
            ./configure --disable-static --enable-debug --enable-werror
            make check
